import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: "category",
      label: "Get started",
      items: [
        "get-started/intro",
        "get-started/installation/index",
        "get-started/quick-start-for-ai",
        "get-started/api-reference",
        "get-started/concepts",
        "get-started/create-your-first-test",
        "get-started/sample-tests",
        "get-started/resources",
      ],
    },
    {
      type: "category",
      label: "Configuration",
      link: {
        type: "generated-index",
        description:
          "Doc Detective tries to have sane defaults, but it also allows for a lot of customization. This section covers the various configuration options available to you.",
      },
      items: ["get-started/config/contexts/index"],
    },
    {
      type: "category",
      label: "Tests",
      link: {
        type: "doc",
        id: "get-started/tests/overview",
      },
      items: [
        "get-started/tests/overview",
        "get-started/tests/standalone",
        "get-started/tests/inline",
        "get-started/tests/detected",
      ],
    },
    {
      type: "category",
      label: "Input formats",
      link: {
        type: "doc",
        id: "get-started/inputs/overview",
      },
      items: [
        "get-started/inputs/overview",
        "get-started/inputs/markdown",
        "get-started/inputs/dita",
        "get-started/inputs/asciidoc",
        "get-started/inputs/html",
        "get-started/inputs/custom",
      ],
    },
    {
      type: "category",
      label: "Actions",
      link: {
        type: "generated-index",
        description:
          "Actions are the commands performed in each step of a test. Each action has a specific purpose, such as checking a link, finding an element, or navigating to a URL.",
      },
      items: [
        "get-started/actions/checkLink",
        "get-started/actions/click",
        "get-started/actions/dragAndDrop",
        "get-started/actions/find",
        "get-started/actions/goTo",
        "get-started/actions/httpRequest",
        "get-started/actions/loadCookie",
        "get-started/actions/loadVariables",
        "get-started/actions/record",
        "get-started/actions/runCode",
        "get-started/actions/runShell",
        "get-started/actions/saveCookie",
        "get-started/actions/screenshot",
        "get-started/actions/stopRecord",
        "get-started/actions/type",
        "get-started/actions/wait",
      ],
    },
    {
      type: "category",
      label: "Selectors",
      link: {
        type: "generated-index",
        description:
          "Selectors are patterns used to select the UI elements you want to interact with in your tests.",
      },
      items: ["get-started/selectors/css", "get-started/selectors/xpath"],
    },
    {
      type: "category",
      label: "Tutorials",
      link: {
        type: "generated-index",
        description:
          "These examples walk through the steps of setting up and running Doc Detective tests.",
      },
      items: [
        "get-started/tutorials/set-up-your-test-environment",
        "get-started/tutorials/fill-fields",
        "get-started/tutorials/capture-screenshot",
        "get-started/tutorials/record-video",
      ],
    },
  ],
  referencesSidebar: [{ type: "autogenerated", dirName: "references" }],
  contributeSidebar: [
    {
      type: "category",
      label: "Contribute to the docs",
      items: [
        "contribute/docs/index",
        "contribute/docs/quick-start",
        "contribute/docs/standard-contributions",
        "contribute/docs/substantial-contributions",
        "contribute/docs/local-development",
        "contribute/docs/review-process",
        // "contribute/testing",
        {
          type: "category",
          label: "Content Templates",
          items: [
            "contribute/docs/templates/how-to",
            "contribute/docs/templates/tutorial",
            "contribute/docs/templates/reference",
            "contribute/docs/templates/feature",
            "contribute/docs/templates/troubleshooting",
          ],
        },
      ],
    },
    // {
    //   type: "category",
    //   label: "Legacy",
    //   items: [{ type: "autogenerated", dirName: "contribute" }],
    // },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
