name: Doc Detective
description: Treat doc content as testable assertions to validate doc accuracy and product UX.
author: Doc Detective
inputs:
  version:
    description: Specify the version of Doc Detective to use instead of the installed default. This can be a specific version number or an NPM tag (like `latest`).
    required: false
    default: latest
  working_directory:
    description: The directory to run the command in, relative to the root of the repository. Defaults to the root of the repository.
    required: false
    default: "."
  config:
    description: Path to the configuration file.
    required: false
  input:
    description: Path to the input file or directory. Overrides the "input" field in the config file.
    required: false
  create_pr_on_change:
    description: Create a pull request if any files in the repo change, such as if screenshots or command results get updated. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  pr_branch:
    description: The name of the branch to create for the pull request. Defaults to `doc-detective-{DATE}`. Only valid if "create_pr_on_change" is set to "true".
    required: false
  pr_title:
    description: The title of the created pull request. Only valid if "create_pr_on_change" is set to "true".
    required: false
    default: "Doc Detective Changes"
  pr_body:
    description: The body of the created pull request. `$RUN_URL` inserts the URL of the workflow run that created the pull request. Only valid if "create_pr_on_change" is set to "true".
    required: false
    default: |
      A Doc Detective run ($RUN_URL) updated files.

      DISCLAIMER: This pull request doesn't reflect whether Doc Detective tests passed for failed, only that files in the repository changed. Review the changes to make sure they're accurate.
  pr_labels:
    description: Comma-separated list of labels to apply to the pull request. Only valid if "create_pr_on_change" is set to "true".
    required: false
    default: "doc-detective"
  pr_assignees:
    description: Comma-separated list of GitHub usernames to assign to the pull request. Only valid if "create_pr_on_change" is set to "true".
    required: false
    default: ""
  pr_reviewers:
    description: Comma-separated list of GitHub usernames to request reviews from for the pull request. Only valid if "create_pr_on_change" is set to "true".
    required: false
    default: ""
  exit_on_fail:
    description: Exit with a non-zero code if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  create_issue_on_fail:
    description: Create a GitHub issue if one or more tests fails. Default is "false". Only valid for the "runTests" command.
    required: false
    default: "false"
  issue_title:
    description: The title of the created GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "Doc Detective Failure"
  issue_body:
    description: The body of the created GitHub issue. `$RESULTS` inserts the results object. `$RUN_URL` inserts the URL of the workflow that created the issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "A Doc Detective run ($RUN_URL) failed with the following results:$RESULTS"
  issue_labels:
    description: Comma-separated list of labels to apply to the GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: "doc-detective"
  issue_assignees:
    description: Comma-separated list of GitHub usernames to assign to the GitHub issue. Only valid if "create_issue_on_fail" is set to "true".
    required: false
    default: ""
  token:
    description: The GitHub token to use for creating issues. Defaults to the token already available to the GitHub Action workflow. Only set this if you want to override the default token.
    required: false
    default: ${{ github.token }}
outputs:
  results:
    description: JSON-formatted results of the command.
runs:
  using: node20 # Specifies the node version
  main: dist/index.js # Path to the JavaScript file that will be executed
branding:
  icon: search # The icon to display in the GitHub Marketplace
  color: green # The color of the branding