blank_issues_enabled: false
contact_links:
  - name: Discord Community
    url: https://discord.gg/2M7wXEThfF
    about: Ask questions and discuss with the community
  - name: Documentation
    url: https://doc-detective.com/docs
    about: Browse the Doc Detective documentation
