name: Lighthouse CI
on: pull_request
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://doc-detective.com
            https://doc-detective.com/docs/get-started/intro
            https://doc-detective.com/docs/get-started
            https://doc-detective.com/docs/category/configuration
            https://doc-detective.com/docs/get-started/config/contexts
            https://doc-detective.com/docs/get-started/tests
            https://doc-detective.com/docs/category/actions
            https://doc-detective.com/docs/get-started/actions/checkLink
            https://doc-detective.com/docs/get-started/actions/find
            https://doc-detective.com/docs/get-started/actions/goTo
            https://doc-detective.com/docs/get-started/actions/httpRequest
            https://doc-detective.com/docs/get-started/actions/runShell
            https://doc-detective.com/docs/get-started/actions/saveScreenshot
            https://doc-detective.com/docs/get-started/actions/setVariables
            https://doc-detective.com/docs/get-started/actions/startRecording
            https://doc-detective.com/docs/get-started/actions/stopRecording
            https://doc-detective.com/docs/get-started/actions/typeKeys
            https://doc-detective.com/docs/get-started/actions/wait
            https://doc-detective.com/docs/category/schemas
            https://doc-detective.com/docs/references/schemas/checkLink
            https://doc-detective.com/docs/references/schemas/config
            https://doc-detective.com/docs/references/schemas/context
            https://doc-detective.com/docs/references/schemas/find
            https://doc-detective.com/docs/references/schemas/goTo
            https://doc-detective.com/docs/references/schemas/httpRequest
            https://doc-detective.com/docs/references/schemas/runShell
            https://doc-detective.com/docs/references/schemas/saveScreenshot
            https://doc-detective.com/docs/references/schemas/setVariables
            https://doc-detective.com/docs/references/schemas/startRecording
            https://doc-detective.com/docs/references/schemas/stopRecording
            https://doc-detective.com/docs/references/schemas/test
            https://doc-detective.com/docs/references/schemas/typeKeys
            https://doc-detective.com/docs/references/schemas/wait
            https://doc-detective.com/app
            https://doc-detective.com/support
            https://doc-detective.com/docs/contribute
            https://doc-detective.com/docs/category/repos
            https://doc-detective.com/docs/contribute/repos/doc-detective
            https://doc-detective.com/docs/contribute/repos/doc-detective-core
            https://doc-detective.com/docs/contribute/repos/doc-detective-common
            https://doc-detective.com/docs/contribute/repos/doc-detective.github.io
            https://doc-detective.com/docs/contribute/repos/github-action
            https://doc-detective.com/docs/contribute/repos/docker-image
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
