name: Extract and Push Markdown Files

on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'

permissions: write-all

jobs:
  extract-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      uses: actions/checkout@v2
      with:
        path: source-repo

    - name: Install Pandoc
      run: sudo apt-get update && sudo apt-get install pandoc -y

    - name: Extract Markdown Files
      run: |
        mkdir -p extracted-markdown
        cd source-repo
        find migrated_docs -type f -name "*.md" | while read f; do
          echo "Extracting $f..."
          filename=$(basename "$f" .md)
          pandoc "$f" -t plain -o "../extracted-markdown/$filename.md"
        done
      shell: bash

    - name: Checkout Target Repository
      uses: actions/checkout@v2
      with:
        repository: team-dev-docs/docdetective-dev-docs
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: target-repo

    - name: Copy Extracted Files to Target Repository
      run: |
        cp -r ../extracted-markdown/* target-repo/

    - name: Commit and Push to Target Repository
      run: |
        cd target-repo
        git config user.email "${GITHUB_ACTOR}"
        git config user.name "${GITHUB_ACTOR}"
        git add .
        git commit -m "Update documentation"
        git push
